version: '3.9'

services:
  ticket_db:
    container_name: ticket-pg-db
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.postgres
    ports:
      - "5433:5432"
    env_file:
      - docker.env
    volumes:
      - ticket-pg-data:/var/lib/postgresql/data
    networks:
      - ticket-network
  ticket_service:
    container_name: ticket-service
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.go.prod
    volumes:
      - ./src:/app
    ports:
      - "8081:8080"
    depends_on:
      - ticket_db
    networks:
      - ticket-network

networks:
  ticket-network:

volumes:
  ticket-pg-data: